server:
  port: 8761
spring:
  application:
    name: discovery-server-app
eureka:
  client:
    register-with-eureka: false # register itself
    fetch-registry: false # fetch info from eureka server
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: 127.0.0.1
  server:
    enable-self-preservation: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"